### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException: 3625

### ISSUE THREAD

**Issue by aibiaoxiaoyu** [bihe0832/AndroidGetAPKInfo#5]
运行java -jar getPackageInfo.jar X.apk 这种命令出错。运行 CheckAndroidV2Signature命令没问题。
java.lang.ArrayIndexOutOfBoundsException: 3625
        at android.content.res.StringBlock.getShort(StringBlock.java:231)
        at android.content.res.StringBlock.getString(StringBlock.java:91)
        at android.content.res.AXmlResourceParser.getName(AXmlResourceParser.java:140)
        at com.bihe0832.packageinfo.utils.AXMLPrinter.getManifestXMLFromAPK(AXMLPrinter.java:64)
        at com.bihe0832.packageinfo.utils.ApkUtil.getApkInfo(ApkUtil.java:27)
        at com.bihe0832.packageinfo.Main.getApkInfo(Main.java:50)
        at com.bihe0832.packageinfo.Main.main(Main.java:38)
org.jdom.input.JDOMParseException: Error on line 2: 文件提前结束。
        at org.jdom.input.SAXBuilder.build(SAXBuilder.java:533)
        at org.jdom.input.SAXBuilder.build(SAXBuilder.java:865)
        at com.bihe0832.packageinfo.utils.ApkUtil.getApkInfo(ApkUtil.java:28)
        at com.bihe0832.packageinfo.Main.getApkInfo(Main.java:50)
        at com.bihe0832.packageinfo.Main.main(Main.java:38)
Caused by: org.xml.sax.SAXParseException; lineNumber: 2; columnNumber: 1; 文件提前结束。
        at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(Unknown Source)
        at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
        at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(Unknown Source)
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(Unknown Source)
        at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
        at org.jdom.input.SAXBuilder.build(SAXBuilder.java:518)
        ... 4 more
Caused by: org.xml.sax.SAXParseException; lineNumber: 2; columnNumber: 1; 文件提前结束。
        at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(Unknown Source)
        at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
        at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(Unknown Source)
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(Unknown Source)
        at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
        at org.jdom.input.SAXBuilder.build(SAXBuilder.java:518)
        at org.jdom.input.SAXBuilder.build(SAXBuilder.java:865)
        at com.bihe0832.packageinfo.utils.ApkUtil.getApkInfo(ApkUtil.java:28)
        at com.bihe0832.packageinfo.Main.getApkInfo(Main.java:50)
        at com.bihe0832.packageinfo.Main.main(Main.java:38)
Caused by: org.xml.sax.SAXParseException; lineNumber: 2; columnNumber: 1; 文件提前结束。
        at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(Unknown Source)
        at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
        at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(Unknown Source)
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(Unknown Source)
        at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
        at org.jdom.input.SAXBuilder.build(SAXBuilder.java:518)
        at org.jdom.input.SAXBuilder.build(SAXBuilder.java:865)
        at com.bihe0832.packageinfo.utils.ApkUtil.getApkInfo(ApkUtil.java:28)
        at com.bihe0832.packageinfo.Main.getApkInfo(Main.java:50)
        at com.bihe0832.packageinfo.Main.main(Main.java:38)

**Comment by bihe0832** [comment]
看异常堆栈应该是解析apk包的AndroidMainfest异常引起的，有可能：

**Comment by bihe0832** [comment]
看异常堆栈应该是解析apk包的AndroidMainfest异常引起的，有可能是该apk包加固过或者使用了特殊的打包方式，如果方便的话邮件我一下对应的apk包，我具体看下~

**Comment by devil2028** [comment]
你好。我也遇到了相同的问题：java.lang.ArrayIndexOutOfBoundsException: 406

我随意执行一个v1+v2签名的apk，就会出现ArrayIndexOutOfBoundsException的问题。

**Comment by bihe0832** [comment]
嗯，问题复现的方法之前已经知道了，确实是必现的。最近因为项目时间比较赶还没来得及修复，我后面尽快改一下~

**Comment by haikelei** [comment]
这个原因能修复一下吗

**Comment by SatanDaddy** [comment]
遇到同样的问题了 =.= 。java.lang.ArrayIndexOutOfBoundsException: 1269
	at android.content.res.StringBlock.getShort(StringBlock.java:231)
	at android.content.res.StringBlock.getString(StringBlock.java:91)
	at android.content.res.AXmlResourceParser.getAttributeValue(AXmlResourceParser.java:290)

**Comment by SatanDaddy** [comment]
也遇到这个问题了。o(╯□╰)o
java.lang.ArrayIndexOutOfBoundsException: 1269
	at android.content.res.StringBlock.getShort(StringBlock.java:231)
	at android.content.res.StringBlock.getString(StringBlock.java:91)
	at android.content.res.AXmlResourceParser.getAttributeValue(AXmlResourceParser.java:290)

**Comment by bihe0832** [comment]
最近多个人邮件我，今天上午临时抽时间修复了一下，最新的master或者[v1.2.0](https://github.com/bihe0832/Android-GetAPKInfo/releases/tag/v1.2.0) 下均为已经修复后的版本。个人验证范围有限，麻烦大家验证确认下~

因为工作原因，一直没有及时修复，让大家久等了~
