### ISSUE TITLE
元素类型 "meta-data" 必须后跟属性规范 ">" 或 "/>"

### ISSUE THREAD

**Issue by paradiseduo** [bihe0832/AndroidGetAPKInfo#6]
```
~/Downloads ❯ java -jar GetMoreAPKInfo.jar ~/Downloads/com.ximalaya.android.sleep_d0bd79e.apk --debug
org.jdom.input.JDOMParseException: Error on line 147: 元素类型 "meta-data" 必须后跟属性规范 ">" 或 "/>"。
	at org.jdom.input.SAXBuilder.build(SAXBuilder.java:533)
	at org.jdom.input.SAXBuilder.build(SAXBuilder.java:865)
	at com.bihe0832.packageinfo.utils.ApkUtil.getApkInfo(ApkUtil.java:28)
	at com.bihe0832.packageinfo.Main.getApkInfo(Main.java:55)
	at com.bihe0832.packageinfo.Main.main(Main.java:43)
```

apk下载地址：
http://down-ww2.537a.com/soft/3/fe/com.ximalaya.android.sleep_d0bd79e.apk

使用apktool解包之后查看AndroidManifest.xml格式是正确的，但是GetMoreAPKInfo无法正确执行。

**Comment by bihe0832** [comment]
收到，我稍候debug确认下

**Comment by bihe0832** [comment]
初步定位还是和之前的issue 一样的问题，官方早期的 AXMLPrinter2 的兼容性不太好。在解析 meta-data 时部分value多了一个 引号导致，目前最新版本已经修复

**Comment by bihe0832** [comment]
问题已修复，使用 https://github.com/bihe0832/Android-GetAPKInfo/releases/tag/V2.0.1  提供的版本即可解决
