### ISSUE TITLE
解析出问题？

### ISSUE THREAD

**Issue by wenwenwen888** [bihe0832/AndroidGetAPKInfo#7]
com.android.apksig.internal.asn1.Asn1DecodingException: com.android.apksig.internal.pkcs7.ContentInfo is not annotated with com.android.apksig.internal.asn1.Asn1Class
	at com.android.apksig.internal.asn1.Asn1BerParser.getContainerAsn1Type(Unknown Source)
	at com.android.apksig.internal.asn1.Asn1BerParser.parse(Unknown Source)
	at com.android.apksig.internal.asn1.Asn1BerParser.parse(Unknown Source)
	at com.android.apksig.internal.apk.v1.V1SchemeVerifier$Signer.verifySigBlockAgainstSigFile(Unknown Source)
	at com.android.apksig.internal.apk.v1.V1SchemeVerifier$Signers.verify(Unknown Source)
	at com.android.apksig.internal.apk.v1.V1SchemeVerifier$Signers.access$100(Unknown Source)
	at com.android.apksig.internal.apk.v1.V1SchemeVerifier.verify(Unknown Source)
	at com.android.apksig.ApkVerifier.verify(Unknown Source)
	at com.android.apksig.ApkVerifier.verify(Unknown Source)
	at com.android.apksigner.ApkSignerTool.verify(Unknown Source)
	at com.bihe0832.packageinfo.Main.a(Unknown Source)
	at com.bihe0832.packageinfo.Main.main(Unknown Source)

**Comment by bihe0832** [comment]
可以给一个遇到问题的APK的下载链接么

**Comment by wenwenwen888** [comment]
```
Caught a exception encoding the public key: com.android.apksig.internal.asn1.Asn1DecodingException: com.android.apksig.internal.x509.SubjectPublicKeyInfo is not annotated with com.android.apksig.internal.asn1.Asn1Class
com.android.apksig.internal.asn1.Asn1DecodingException: com.android.apksig.internal.x509.SubjectPublicKeyInfo is not annotated with com.android.apksig.internal.asn1.Asn1Class
	at com.android.apksig.internal.asn1.Asn1BerParser.getContainerAsn1Type(Unknown Source)
	at com.android.apksig.internal.asn1.Asn1BerParser.parse(Unknown Source)
	at com.android.apksig.internal.asn1.Asn1BerParser.parse(Unknown Source)
	at com.android.apksig.internal.apk.ApkSigningBlockUtils.encodePublicKey(Unknown Source)
	at com.android.apksig.internal.apk.v2.V2SchemeVerifier.parseSigner(Unknown Source)
	at com.android.apksig.internal.apk.v2.V2SchemeVerifier.parseSigners(Unknown Source)
	at com.android.apksig.internal.apk.v2.V2SchemeVerifier.verify(Unknown Source)
	at com.android.apksig.internal.apk.v2.V2SchemeVerifier.verify(Unknown Source)
	at com.android.apksig.ApkVerifier.verify(Unknown Source)
	at com.android.apksig.ApkVerifier.verify(Unknown Source)
	at com.android.apksigner.ApkSignerTool.verify(Unknown Source)
	at com.bihe0832.packageinfo.Main.a(Unknown Source)
	at com.bihe0832.packageinfo.Main.main(Unknown Source)
com.android.apksig.internal.asn1.Asn1DecodingException: com.android.apksig.internal.pkcs7.ContentInfo is not annotated with com.android.apksig.internal.asn1.Asn1Class
	at com.android.apksig.internal.asn1.Asn1BerParser.getContainerAsn1Type(Unknown Source)
	at com.android.apksig.internal.asn1.Asn1BerParser.parse(Unknown Source)
	at com.android.apksig.internal.asn1.Asn1BerParser.parse(Unknown Source)
	at com.android.apksig.internal.apk.v1.V1SchemeVerifier$Signer.verifySigBlockAgainstSigFile(Unknown Source)
	at com.android.apksig.internal.apk.v1.V1SchemeVerifier$Signers.verify(Unknown Source)
	at com.android.apksig.internal.apk.v1.V1SchemeVerifier$Signers.access$100(Unknown Source)
	at com.android.apksig.internal.apk.v1.V1SchemeVerifier.verify(Unknown Source)
	at com.android.apksig.ApkVerifier.verify(Unknown Source)
	at com.android.apksig.ApkVerifier.verify(Unknown Source)
	at com.android.apksigner.ApkSignerTool.verify(Unknown Source)
	at com.bihe0832.packageinfo.Main.a(Unknown Source)
	at com.bihe0832.packageinfo.Main.main(Unknown Source)
```
你好，估计不是apk包的问题，我这边无论用v1还是v2签名，都会报错误。试过用来查微信、豆瓣的客户端都会出这问题。

**Comment by wenwenwen888** [comment]
单独用CheckAndroidSignature.jar没问题

**Comment by bihe0832** [comment]
源码运行还是使用哪个版本的jar包？

**Comment by wenwenwen888** [comment]
用的是最新的GetAPKInfo.jar

**Comment by bihe0832** [comment]
➜  Android-GetAPKInfo git:(master) ✗ java -version
java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)

我用项目根目录的jar测试没有问题，提供一下你的 java 版本号

**Comment by wenwenwen888** [comment]
java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)

**Comment by bihe0832** [comment]
怀疑是当时编release版本遇到了异常没注意，刚才用根目录的 Jar 可以用；最新的release的有问题，我已经手动更新了最新的release的 Jar， @wenwenwen888 使用根目录的Jar或者点击链接  https://github.com/bihe0832/Android-GetAPKInfo/releases/download/V2.0.1/GetAPKInfo.jar （MD5:f7312bf1113af189cba98bbddcd4affe） 下载最新的Jar试试

**Comment by wenwenwen888** [comment]
牛逼，可以了。感谢老哥
